### ISSUE TITLE
and/or typo 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/sql-aggregate-functions-readme#16]
Near Top of Lesson, under subtitle, "Aggregate Functions", this line is missing the / in the 'and or' . 

"We'll craft queries that select a desired set of values from a table and then aggregate that data using the above aggregators, in addition to clauses that will group and or order the returned data based on various conditions."

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
